[package]
name = "rn_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Core NES emulation engine"
license.workspace = true

[dependencies]
anyhow.workspace = true
lazy_static.workspace = true
log.workspace = true
parse-display.workspace = true
regex.workspace = true
thiserror.workspace = true
serde.workspace = true