[package]
name = "rn_ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "UI components for the RustNES emulator"
license.workspace = true

[[bin]]
name = "rn_ui"
path = "src/main.rs"

[dependencies]
rn_core = { path = "../rn_core" }

anyhow.workspace = true
eframe.workspace = true
egui.workspace = true
tracing-subscriber.workspace = true
