[package]
name = "rn_audio"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Audio output for the NES emulator"
license.workspace = true

[dependencies]
rn_core = { path = "../rn_core" }

cpal.workspace = true
anyhow.workspace = true
log.workspace = true
ringbuf.workspace = true
