[package]
name = "rn_input"
description = "Input handling and configuration for RustNES"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rn_core = { path = "../rn_core" } 

[lints]
workspace = true
