[book]
title = "Building a NES Emulator in Rust"
authors = ["Pietrino Atzeni"]
description = "A step-by-step guide to building a NES emulator in Rust, following a test-driven development approach."
src = "src"
language = "en"

[output.html]
git-repository-url = "https://github.com/beoboo/rustnes"
edit-url-template = "https://github.com/beoboo/rustnes/edit/main/book/{path}"
#additional-css = ["custom.css"]
#additional-js = ["custom.js"]
preferred-dark-theme = "navy"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 20
