[book]
title = "Building a NES Emulator in Rust"
authors = ["Pietrino Atzeni"]
description = "A step-by-step guide to building a NES emulator in Rust, following a test-driven development approach."
src = "src"
language = "en"
multilingual = false

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/beoboo/rustnes"
edit-url-template = "https://github.com/beoboo/rustnes/edit/main/book/{path}"
additional-css = ["theme/css/track-styles.css"]
#additional-js = ["custom.js"]
no-section-label = false
smart-punctuation = true
mathjax-support = false
copy-fonts = true
# Ensures sidebar is always visible
sidebarnav-theme = "always-visible"
sidebar-hidden = false
sidebar-width = "300px"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 20
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true

[output.html.fold]
enable = false
level = 0
